// Code generated by go-swagger; DO NOT EDIT.

package baz_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/AlekSi/grpc-gateway-swagger-issue/api/swagger/models"
)

// BazReader is a Reader for the Baz structure.
type BazReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BazReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBazOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBazOK creates a BazOK with default headers values
func NewBazOK() *BazOK {
	return &BazOK{}
}

/*BazOK handles this case with default header values.

A successful response.
*/
type BazOK struct {
	Payload *models.APIBazResponse
}

func (o *BazOK) Error() string {
	return fmt.Sprintf("[POST /Baz][%d] bazOK  %+v", 200, o.Payload)
}

func (o *BazOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIBazResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
