// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/baz.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BazRequest struct {
	Common               *Common  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BazRequest) Reset()         { *m = BazRequest{} }
func (m *BazRequest) String() string { return proto.CompactTextString(m) }
func (*BazRequest) ProtoMessage()    {}
func (*BazRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baz_47a225072b9bf23a, []int{0}
}
func (m *BazRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BazRequest.Unmarshal(m, b)
}
func (m *BazRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BazRequest.Marshal(b, m, deterministic)
}
func (dst *BazRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BazRequest.Merge(dst, src)
}
func (m *BazRequest) XXX_Size() int {
	return xxx_messageInfo_BazRequest.Size(m)
}
func (m *BazRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BazRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BazRequest proto.InternalMessageInfo

func (m *BazRequest) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

type BazResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BazResponse) Reset()         { *m = BazResponse{} }
func (m *BazResponse) String() string { return proto.CompactTextString(m) }
func (*BazResponse) ProtoMessage()    {}
func (*BazResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baz_47a225072b9bf23a, []int{1}
}
func (m *BazResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BazResponse.Unmarshal(m, b)
}
func (m *BazResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BazResponse.Marshal(b, m, deterministic)
}
func (dst *BazResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BazResponse.Merge(dst, src)
}
func (m *BazResponse) XXX_Size() int {
	return xxx_messageInfo_BazResponse.Size(m)
}
func (m *BazResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BazResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BazResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BazRequest)(nil), "api.BazRequest")
	proto.RegisterType((*BazResponse)(nil), "api.BazResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BazServiceClient is the client API for BazService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BazServiceClient interface {
	Baz(ctx context.Context, in *BazRequest, opts ...grpc.CallOption) (*BazResponse, error)
}

type bazServiceClient struct {
	cc *grpc.ClientConn
}

func NewBazServiceClient(cc *grpc.ClientConn) BazServiceClient {
	return &bazServiceClient{cc}
}

func (c *bazServiceClient) Baz(ctx context.Context, in *BazRequest, opts ...grpc.CallOption) (*BazResponse, error) {
	out := new(BazResponse)
	err := c.cc.Invoke(ctx, "/api.BazService/Baz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BazServiceServer is the server API for BazService service.
type BazServiceServer interface {
	Baz(context.Context, *BazRequest) (*BazResponse, error)
}

func RegisterBazServiceServer(s *grpc.Server, srv BazServiceServer) {
	s.RegisterService(&_BazService_serviceDesc, srv)
}

func _BazService_Baz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BazRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BazServiceServer).Baz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BazService/Baz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BazServiceServer).Baz(ctx, req.(*BazRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BazService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BazService",
	HandlerType: (*BazServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Baz",
			Handler:    _BazService_Baz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/baz.proto",
}

func init() { proto.RegisterFile("api/baz.proto", fileDescriptor_baz_47a225072b9bf23a) }

var fileDescriptor_baz_47a225072b9bf23a = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x4a, 0xac, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x92,
	0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x49, 0x25, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96,
	0x64, 0xe6, 0xe7, 0x15, 0x43, 0x94, 0x48, 0x09, 0x80, 0x84, 0x93, 0xf3, 0x73, 0x73, 0xf3, 0xf3,
	0x20, 0x22, 0x4a, 0x86, 0x5c, 0x5c, 0x4e, 0x89, 0x55, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0xca, 0x5c, 0x6c, 0x10, 0x59, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x6e, 0xbd, 0xc4,
	0x82, 0x4c, 0x3d, 0x67, 0xb0, 0x50, 0x10, 0x54, 0x4a, 0x89, 0x97, 0x8b, 0x1b, 0xac, 0xa5, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0xd5, 0xc8, 0x1d, 0x6c, 0x42, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa,
	0x90, 0x25, 0x17, 0xb3, 0x53, 0x62, 0x95, 0x10, 0x3f, 0x58, 0x23, 0xc2, 0x64, 0x29, 0x01, 0x84,
	0x00, 0x44, 0x9f, 0x12, 0x7f, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x38, 0x95, 0x58, 0xf4, 0x9d, 0x12,
	0xab, 0xac, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0x2e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x99,
	0x04, 0xb7, 0x1a, 0xd7, 0x00, 0x00, 0x00,
}
